"""empty message

Revision ID: 14bdd204a317
Revises: edd25f8319cc
Create Date: 2018-12-07 12:55:56.619606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14bdd204a317'
down_revision = 'edd25f8319cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('userid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'businesses', 'users', ['userid'], ['id'])
    op.drop_constraint('users_businessesid_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'businessesid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('businessesid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_businessesid_fkey', 'users', 'businesses', ['businessesid'], ['id'])
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'userid')
    # ### end Alembic commands ###
