"""empty message

Revision ID: a020bf35fc99
Revises: 
Create Date: 2018-12-06 00:22:19.670765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a020bf35fc99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('businessesid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'businesses', ['businessesid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'businessesid')
    # ### end Alembic commands ###
